### ISSUE TITLE
Lazy loading in web workers

### ISSUE THREAD

**Issue by elf-pavlik** [PolymerLabs/actor-boilerplate#15]
Many presentations from recent Google I/O focused on sophisticated code splitting and lazy loading. Could you include examples how to do it in actors which could run in web workers?
For example based on some message specific state reducer could get loaded, or some REST service API component would get loaded only when it needs to use some specific part of that API.

**Comment by arjunyel** [comment]
Blocked on ES Modules in workers https://bugs.chromium.org/p/chromium/issues/detail?id=680046

**Comment by surma** [comment]
@arjunyel That's not true!

@elf-pavlik Sorry, I must have lost this email. 

`actor-boilerplate` uses rollup with a custom loader, so you can just use dynamic import for code splitting and lazy loading. `actor-boilerplate` will make it work in workers.
