### ISSUE TITLE
Build do not copy statics file

### ISSUE THREAD

**Issue by rubenslopes** [PolymerLabs/actor-boilerplate#5]
I'm on demo/clock branch and got the following output

![image](https://user-images.githubusercontent.com/1854412/48522304-ee70c700-e856-11e8-86ae-73564ecc1a1f.png)

and that is my final dist folder

![image](https://user-images.githubusercontent.com/1854412/48522236-a81b6800-e856-11e8-9bec-7903bd19d7e6.png)

not really sure how to proceed 😞

**Comment by surma** [comment]
It seems to work for me.

Your screenshows that `npm run copy-static` is about to be run. Are you sure there’s no static files in there? What’s the output of `git status`?

<img width="841" alt="screen shot 2018-11-14 at 4 50 35 pm" src="https://user-images.githubusercontent.com/234957/48522405-704bfa80-e82d-11e8-909d-d4898f6c6f10.png">

**Comment by rubenslopes** [comment]
![image](https://user-images.githubusercontent.com/1854412/48522728-84f1b800-e858-11e8-803b-4ef42db14221.png)

**Comment by surma** [comment]
Hm I wonder if this is a Windows issue. Can you post the full built output?

**Comment by rubenslopes** [comment]
I don't have much experience with powershell is that what you meant?
![image](https://user-images.githubusercontent.com/1854412/48523214-4ceb7480-e85a-11e8-9f14-a1237c3cf0e8.png)

`log.txt`

>\> actor-boilerplate@0.0.1 build D:\projects\actor-boilerplate
>\> rollup -c && npm run copy-static && npm run gzip
>
>\> actor-boilerplate@0.0.1 copy-static D:\projects\actor-boilerplate
>\> cpx 'static/**' dist
>
>\> actor-boilerplate@0.0.1 gzip D:\projects\actor-boilerplate
>\> gzip -k9nr dist

**Comment by surma** [comment]
Ha, I think that solves the mystery, actually. I don’t have a windows machine at hand, but I’m using `/` in the `cpx` command.

For now, you can just copy all the files from `static` into `dist` so you can keep going.

I’ll fix this properly when I’m back from travel :)

**Comment by akuma06** [comment]
@rubenslopes The fact that `cpx` is not recognized by windows powershell as a command is a correct behavior since `cpx` should be installed as a local dependency.

@surma It works fine for me on windows when the argument for `cpx` is `cpx static/**/ dist/`. Actually, on windows (if I remember correctly), you can't use single quotes in command line. So you just have to remove or replace them with escaped double quotes.

Therefore, the command in demo-clock's package.json should be either :

```
scripts: {
  "copy-static": "cpx static/** dist"
  ...
}
``` 

or 

```
scripts: {
  "copy-static": "cpx \"static/**\" dist"
  ...
}
``` 

Both have been tested and seem to work on windows (and should work on linux as well). Didn't try on Mac.

**Comment by TimvdLippe** [comment]
@akuma06 that's awesome! Do you mind opening a PR with the fixes?

**Comment by akuma06** [comment]
I don't think I can do one PR for two completely different branches, so I just made two PR. Hoping I'm not spamming.

**Comment by TimvdLippe** [comment]
No spam at all, I was expecting exactly two PRs :) I will be able to test
your PRs on Monday.

**Comment by TimvdLippe** [comment]
This should now be fixed for both demos.
