### ISSUE TITLE
package-lock.json references local directory for actor-helpers

### ISSUE THREAD

**Issue by rgfoley** [PolymerLabs/actor-boilerplate#9]
As the title says, while package.json references the actor-helpers repo, the package-lock references a local version of the actor-helpers repo via a file:// url, causing an error on install.

![screenshot from 2018-11-20 18-27-19](https://user-images.githubusercontent.com/7256749/48809294-0aaab300-ecf2-11e8-9e5c-cfb14d440617.png)

**Comment by TimvdLippe** [comment]
Thanks for the report! It should now be fixed :smile:
